add Junit formatter to usage in ci/cd environments
shipmonk-rnd/composer-dependency-analyser pull request #110
Opened 2024-03-22 20:59 UTC by reinfi

Hey, 
first, awesome work!

We introduced this library a few days ago and it works perfect for us. 

To use it in our CI/CD pipeline we would need a junit output because otherwise we would need to stop right after the run of this library, but we have about 25 different programs running for different stuff. 

That's why I implemented a JunitFormatter. Hopefully this is fine for you. 

Looking forward for your feedback.

2024-03-25 10:57 UTC, janedbal requested changes
> I have no idea why the two tests are failing. Help would be really appreciated

Dont worry about that. Composer autoloader is prepended and it causes old versions of classes from composer-dependency-analyser (from the tested package) to be used. I kinda thought this wont happen that often so I didnt fix it yet. Seeing this now, I'll.

2024-03-25 10:57 UTC, janedbal commented on src/Result/FormatterInterface.php
> +interface FormatterInterface
We try to avoid Interface suffixes. This should be `ResultFormatter` and the old implementor probably `ConsoleFormatter`

2024-03-25 10:57 UTC, janedbal commented on tests/JunitFormatterTest.php
> +        // editorconfig-checker-disable
Most probably not needed here.

2024-03-25 10:57 UTC, janedbal commented on src/Initializer.php
> +    --format <format>           i.e. default or junit, can be omitted
`Change output format. Available values: console (default), junit`

2024-03-25 10:57 UTC, janedbal commented on src/Initializer.php
> +                return new ResultFormatter($this->cwd, $this->printer);
Lets be strict here. 

- empty or 'console' uses the default one
- 'junit' uses the new one
- anything else results in a failure (`InvalidConfigException`).

2024-03-25 10:57 UTC, janedbal commented on src/Initializer.php
> +                return new ResultFormatter($this->cwd, $this->printer);
Ideally add simple test to BinTest.

2024-03-25 10:57 UTC, janedbal commented on README.md
> +- `--format` to use different output format, i.e. junit (supported is junit/default).
`to use different output format, available are: console (default), junit`

2024-03-25 11:03 UTC, janedbal commented on src/Result/JunitFormatter.php
> +    public const VERBOSE_SHOWN_USAGES = 3;
Lets move this to the interface.

2024-03-25 13:12 UTC, janedbal commented
I just [fixed the e2e autoloader issue](https://github.com/shipmonk-rnd/composer-dependency-analyser/pull/111) and rebased your branch.

2024-03-25 20:03 UTC, reinfi commented on tests/JunitFormatterTest.php
> +        // editorconfig-checker-disable
was c&p from other test, removed it

2024-04-04 09:39 UTC, janedbal approved these changes
Looks good, please rebase and I'll merge it. Thank you

2024-04-04 09:41 UTC, merged